const brands = [
  { name: "Nike", sites: ["무신사 / Musinsa", "Kith", "GOAT", "StockX", "Sneakersnstuff", "End Clothing", "ASOS"] },
  { name: "Adidas", sites: ["무신사 / Musinsa", "Kith", "GOAT", "StockX", "Sneakersnstuff", "End Clothing", "ASOS"] },
  { name: "New Balance", sites: ["무신사 / Musinsa", "Kith", "GOAT", "StockX", "Sneakersnstuff", "End Clothing"] },
  { name: "Gucci", sites: ["SSENSE", "Mytheresa", "Net-a-Porter", "Farfetch", "Vestiaire Collective"] },
  { name: "Prada", sites: ["SSENSE", "Mytheresa", "Net-a-Porter", "Farfetch", "Vestiaire Collective"] },
  { name: "Balenciaga", sites: ["SSENSE", "Mytheresa", "Net-a-Porter", "Farfetch", "Vestiaire Collective"] },
  { name: "Louis Vuitton", sites: ["Vestiaire Collective", "크림 / KREAM", "Grailed"] },
  { name: "Chanel", sites: ["Vestiaire Collective", "크림 / KREAM", "Grailed"] },
  { name: "Dior", sites: ["SSENSE", "Mytheresa", "Farfetch", "Vestiaire Collective", "크림 / KREAM"] },
  { name: "Saint Laurent", sites: ["SSENSE", "Mytheresa", "Net-a-Porter", "Farfetch", "Vestiaire Collective"] },
  { name: "Bottega Veneta", sites: ["SSENSE", "Mytheresa", "Net-a-Porter", "Farfetch", "Vestiaire Collective"] },
  { name: "Maison Margiela", sites: ["SSENSE", "Mytheresa", "Farfetch", "End Clothing", "Dover Street Market"] },
  { name: "Rick Owens", sites: ["SSENSE", "Farfetch", "Grailed", "Dover Street Market"] },
  { name: "Acne Studios", sites: ["SSENSE", "Mytheresa", "Net-a-Porter", "Farfetch", "End Clothing"] },
  { name: "Ami Paris", sites: ["SSENSE", "Mytheresa", "Farfetch", "End Clothing", "29CM"] },
  { name: "Stone Island", sites: ["SSENSE", "Farfetch", "End Clothing", "Dover Street Market"] },
  { name: "Moncler", sites: ["SSENSE", "Mytheresa", "Farfetch", "End Clothing"] },
  { name: "The North Face", sites: ["무신사 / Musinsa", "End Clothing", "ASOS", "Kith"] },
  { name: "Stussy", sites: ["Dover Street Market", "End Clothing", "Kith", "무신사 / Musinsa"] },
  { name: "Supreme", sites: ["Supreme", "StockX", "Grailed", "크림 / KREAM", "Dover Street Market"] },
  { name: "Palace", sites: ["Palace", "StockX", "Grailed", "End Clothing", "Dover Street Market"] },
  { name: "Off-White", sites: ["SSENSE", "Farfetch", "StockX", "Grailed", "End Clothing"] },
  { name: "Fear of God", sites: ["SSENSE", "Farfetch", "Grailed", "Kith", "Dover Street Market"] },
  { name: "Comme des Garcons", sites: ["Dover Street Market", "SSENSE", "Farfetch", "End Clothing"] },
  { name: "Thom Browne", sites: ["SSENSE", "Mytheresa", "Farfetch", "W Concept", "한섬 EQL"] },
  { name: "Burberry", sites: ["SSENSE", "Mytheresa", "Net-a-Porter", "Farfetch", "Vestiaire Collective"] },
  { name: "Valentino", sites: ["SSENSE", "Mytheresa", "Net-a-Porter", "Farfetch"] },
  { name: "Alexander McQueen", sites: ["SSENSE", "Mytheresa", "Net-a-Porter", "Farfetch", "StockX"] },
  { name: "Loewe", sites: ["SSENSE", "Mytheresa", "Net-a-Porter", "Farfetch"] },
  { name: "Jacquemus", sites: ["SSENSE", "Mytheresa", "Net-a-Porter", "Farfetch"] },
  { name: "Jordan", sites: ["GOAT", "StockX", "Kicks Crew", "Sneakersnstuff", "크림 / KREAM"] },
  { name: "Converse", sites: ["무신사 / Musinsa", "ASOS", "End Clothing", "Kith"] },
  { name: "Vans", sites: ["무신사 / Musinsa", "ASOS", "End Clothing"] },
  { name: "Asics", sites: ["Kith", "End Clothing", "Sneakersnstuff", "GOAT", "StockX"] },
  { name: "Salomon", sites: ["SSENSE", "End Clothing", "Dover Street Market", "무신사 / Musinsa"] },
  { name: "Zara", sites: ["Zara"] },
  { name: "Uniqlo", sites: ["Uniqlo"] },
  { name: "COS", sites: ["ASOS", "W Concept"] },
  { name: "Vivienne Westwood", sites: ["SSENSE", "Farfetch", "End Clothing", "Vestiaire Collective"] },
  { name: "Versace", sites: ["SSENSE", "Mytheresa", "Net-a-Porter", "Farfetch", "Vestiaire Collective"] }
];
